stages:
  - deploy

deploy-maps:
  stage: deploy
  image: node:20
  only:
    - master
  variables:
    UPLOAD_MODE: "MAP_STORAGE"
    MAP_STORAGE_URL: "https://office.videodocker.com/map-storage"
    UPLOAD_DIRECTORY: "kanto-region"
    SKIP_MAP_OPTIMIZER: "true"
  script:
    - npm ci
    - npm run buildmap
    - cp -r public/* dist/
    - rm -rf dist/maps/src
    - SCRIPT_JS=$(basename dist/assets/maps-src-main-*.js) && for tmj in dist/maps/*.tmj; do sed -i "s|src\\/main\.ts|../assets/$SCRIPT_JS|g" "$tmj"; done
    - npm run upload-only
  environment:
    name: production
    url: https://office.videodocker.com
